/** Latest BBP §1.7. Ranges stay ranges in the description; no arbitrary
 * midpoint is presented as a client-approved typical duration. */
export const BBP_STAGE_SEED = [
  { stage_code: 'QUARANTINE', stage_name: 'Quarantine', stage_category: 'PRE_PRODUCTIVE', stage_sequence: 1, typical_duration_days: 28, min_days_before_move: 0, transition_trigger: 'MANUAL', next_stage_code: 'GILT_REARING', data_entry_form: 'STANDARD', show_on_animal_card: true, stage_description: 'BBP §1.7: Weeks 1–4. Release requires the quarantine process; elapsed time alone is not clearance.' },
  { stage_code: 'GILT_REARING', stage_name: 'Gilt Rearing', stage_category: 'PRE_PRODUCTIVE', stage_sequence: 2, typical_duration_days: 210, min_days_before_move: 0, transition_trigger: 'MANUAL', next_stage_code: 'FLUSH', data_entry_form: 'STANDARD', show_on_animal_card: true, stage_description: 'BBP §1.7: Weeks 4–34 (approximately 210 days). Selection and service readiness require recorded checkpoints.' },
  { stage_code: 'DRY_PERIOD', stage_name: 'Dry Period', stage_category: 'PRE_PRODUCTIVE', stage_sequence: 3, min_days_before_move: 4, transition_trigger: 'EVENT_BASED', next_stage_code: 'FLUSH', data_entry_form: 'STANDARD', show_on_animal_card: true, stage_description: 'BBP §1.7: 4–7 days after weaning, before flushing. No single typical day has been specified.' },
  { stage_code: 'FLUSH', stage_name: 'Flush', stage_category: 'PRE_PRODUCTIVE', stage_sequence: 4, min_days_before_move: 3, transition_trigger: 'EVENT_BASED', next_stage_code: 'INSEMINATION', data_entry_form: 'STANDARD', show_on_animal_card: true, stage_description: 'BBP §1.7: 3–5 days. Flushing is separate from insemination; no single typical day has been specified.' },
  { stage_code: 'INSEMINATION', stage_name: 'Insemination', stage_category: 'PRODUCTIVE', stage_sequence: 5, typical_duration_days: 2, min_days_before_move: 0, transition_trigger: 'EVENT_BASED', next_stage_code: 'GESTATION', data_entry_form: 'STANDARD', show_on_animal_card: true, stage_description: 'BBP §1.7: 2 days. Record insemination events; pregnancy checks remain separate events.' },
  { stage_code: 'GESTATION', stage_name: 'Gestation', stage_category: 'PRODUCTIVE', stage_sequence: 6, typical_duration_days: 116, min_days_before_move: 0, transition_trigger: 'EVENT_BASED', next_stage_code: 'FARROWING', data_entry_form: 'STANDARD', show_on_animal_card: true, stage_description: 'BBP §1.7: 116 days. Pregnancy scan and farrowing events govern progression.' },
  { stage_code: 'FARROWING', stage_name: 'Farrowing', stage_category: 'OUTPUT', stage_sequence: 7, min_days_before_move: 2, transition_trigger: 'EVENT_BASED', next_stage_code: 'LACTATION', data_entry_form: 'FARROWING', show_on_animal_card: true, stage_description: 'BBP §1.7: 2–4 days. Record the litter; no single typical day has been specified.' },
  { stage_code: 'LACTATION', stage_name: 'Lactation', stage_category: 'PRODUCTIVE', stage_sequence: 8, typical_duration_days: 28, min_days_before_move: 0, transition_trigger: 'EVENT_BASED', next_stage_code: 'DRY_PERIOD', data_entry_form: 'STANDARD', show_on_animal_card: true, stage_description: 'BBP §1.7: 28 days. Weaning POST returns the sow to Dry Period; weaning is an event, not a separate breeding stage.' },
] as const;

/** Only unambiguous identity renames. FLUSH_SERVICE is deliberately absent:
 * it combines two newly separate stages and cannot be remapped by guessing. */
export const BBP_STAGE_RENAMES: Readonly<Record<string, string>> = { GILT_GROWER: 'GILT_REARING', DRY_SOW_GESTATION: 'GESTATION' };
